### ISSUE TITLE
Ruby CSV

### ISSUE THREAD

**Issue by jonmagic** [jonmagic/csvdiff-ruby#3]
I had no idea the Ruby CSV library could [do all of this](http://technicalpickles.com/posts/parsing-csv-with-ruby/). Thank you @technicalpickles this may save us some time :+1:

**Comment by gjtorikian** [comment]
I thought we were already going to go through the standard library? It's what we use to render them, too.

**Comment by gjtorikian** [comment]
Ah, nevermind, I see what you mean. The array of hashes is pretty neat. Wonder how this would work for files with non-useful first rows.

**Comment by technicalpickles** [comment]
![the more you know](http://stream1.gifsoup.com/view/204031/the-more-you-know-o.gif)

I think you kind of have to know ahead of time if the first line is meaningful.

Even if you don't have useful headers, you can still use the converters to change numerics and datetimes to their ruby types, to compare those.

**Comment by jonmagic** [comment]
> Even if you don't have useful headers, you can still use the converters to change numerics and datetimes to their ruby types, to compare those.

That is the part I am interested in :)
